// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.15.8
// source: tp-term.proto

package tpterm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nonce           int64  `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	TransactionData []byte `protobuf:"bytes,2,opt,name=transaction_data,json=transactionData,proto3" json:"transaction_data,omitempty"` // full arbitrary transaction data
	// Metadata
	Amount int64 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"` // amount in lowest denomination of currency (USD -> cents,
	// so $0.01 == 1 and $1.00 == 100)
	CardNumber string `protobuf:"bytes,4,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"` // card number as a string
	CardExp    string `protobuf:"bytes,5,opt,name=card_exp,json=cardExp,proto3" json:"card_exp,omitempty"`          // card expiration as as string
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tp_term_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_tp_term_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_tp_term_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetNonce() int64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *Transaction) GetTransactionData() []byte {
	if x != nil {
		return x.TransactionData
	}
	return nil
}

func (x *Transaction) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *Transaction) GetCardExp() string {
	if x != nil {
		return x.CardExp
	}
	return ""
}

type TransactionSignature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransactionSignature []byte `protobuf:"bytes,1,opt,name=transaction_signature,json=transactionSignature,proto3" json:"transaction_signature,omitempty"`
}

func (x *TransactionSignature) Reset() {
	*x = TransactionSignature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tp_term_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionSignature) ProtoMessage() {}

func (x *TransactionSignature) ProtoReflect() protoreflect.Message {
	mi := &file_tp_term_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionSignature.ProtoReflect.Descriptor instead.
func (*TransactionSignature) Descriptor() ([]byte, []int) {
	return file_tp_term_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionSignature) GetTransactionSignature() []byte {
	if x != nil {
		return x.TransactionSignature
	}
	return nil
}

var File_tp_term_proto protoreflect.FileDescriptor

var file_tp_term_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x74, 0x70, 0x2d, 0x74, 0x65, 0x72, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xa2, 0x01, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x72, 0x64,
	0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63,
	0x61, 0x72, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x61, 0x72,
	0x64, 0x5f, 0x65, 0x78, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x61, 0x72,
	0x64, 0x45, 0x78, 0x70, 0x22, 0x4b, 0x0a, 0x14, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x33, 0x0a, 0x15,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x14, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x32, 0x3e, 0x0a, 0x06, 0x54, 0x50, 0x54, 0x65, 0x72, 0x6d, 0x12, 0x34, 0x0a, 0x0b, 0x53,
	0x69, 0x67, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x2e, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x15, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22,
	0x00, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x54, 0x72, 0x75, 0x73, 0x74, 0x65, 0x64, 0x50, 0x61, 0x79, 0x2f, 0x74, 0x70, 0x2d, 0x74, 0x65,
	0x72, 0x6d, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x74, 0x70, 0x74, 0x65, 0x72, 0x6d, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tp_term_proto_rawDescOnce sync.Once
	file_tp_term_proto_rawDescData = file_tp_term_proto_rawDesc
)

func file_tp_term_proto_rawDescGZIP() []byte {
	file_tp_term_proto_rawDescOnce.Do(func() {
		file_tp_term_proto_rawDescData = protoimpl.X.CompressGZIP(file_tp_term_proto_rawDescData)
	})
	return file_tp_term_proto_rawDescData
}

var file_tp_term_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tp_term_proto_goTypes = []interface{}{
	(*Transaction)(nil),          // 0: Transaction
	(*TransactionSignature)(nil), // 1: TransactionSignature
}
var file_tp_term_proto_depIdxs = []int32{
	0, // 0: TPTerm.SignRequest:input_type -> Transaction
	1, // 1: TPTerm.SignRequest:output_type -> TransactionSignature
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tp_term_proto_init() }
func file_tp_term_proto_init() {
	if File_tp_term_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tp_term_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Transaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tp_term_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactionSignature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tp_term_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tp_term_proto_goTypes,
		DependencyIndexes: file_tp_term_proto_depIdxs,
		MessageInfos:      file_tp_term_proto_msgTypes,
	}.Build()
	File_tp_term_proto = out.File
	file_tp_term_proto_rawDesc = nil
	file_tp_term_proto_goTypes = nil
	file_tp_term_proto_depIdxs = nil
}
